ALTER TABLE trades ALTER COLUMN result_r DROP NOT NULL;

ALTER TABLE trades ADD COLUMN IF NOT EXISTS buy_price NUMERIC(14, 2);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS sell_price NUMERIC(14, 2);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS bought_time TIMESTAMPTZ;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS sold_time TIMESTAMPTZ;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS holding_time_text VARCHAR(64);
